commit

diff --git a/files/image-builder/ubuntu2004/rstudio-component.yaml b/files/image-builder/ubuntu2004/rstudio-component.yaml
--- a/files/image-builder/ubuntu2004/rstudio-component.yaml
+++ b/files/image-builder/ubuntu2004/rstudio-component.yaml
@@ -62,6 +62,7 @@ phases:
               add-apt-repository -y "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
               add-apt-repository -y ppa:c2d4u.team/c2d4u4.0+
               apt-get update -y
+              sudo apt-get install -y gdebi-core
               apt install --no-install-recommends -y r-base
               apt install -y --no-install-recommends r-cran-rstan
               apt install -y --no-install-recommends r-cran-tidyverse
@@ -78,17 +79,28 @@ phases:
               fi
 
               apt install -y ./rstudio-2022.12.0-353-amd64.deb
-              sudo systemctl daemon-reload
-              sudo rstudio-server stop || echo "Unable to stop rstudio server"
 
               ################################################
               # Install Shiny Server
               ################################################
+
+              FILE="rstudio-server-2022.12.0-353-amd64.deb"
+              if [ -f "$FILE" ]; then
+                echo "$FILE exists."
+              else
+                wget https://download2.rstudio.org/server/bionic/amd64/rstudio-server-2022.12.0-353-amd64.deb
+              fi
+
+              apt install -y rstudio-server-2022.12.0-353-amd64.deb
+
+              sudo systemctl daemon-reload
+              sudo rstudio-server stop || echo "Unable to stop rstudio server"
+              ################################################
+              # Install Shiny Server
+              ################################################
               Rscript -e "install.packages(c('shiny'), repos='https://cran.rstudio.com')"
-              apt-get install -y gdebi-core
               wget https://download3.rstudio.org/ubuntu-18.04/x86_64/shiny-server-1.5.20.1002-amd64.deb
               apt install -y shiny-server-1.5.20.1002-amd64.deb
-
 
               ################################################
               # Install R packages
@@ -110,6 +122,8 @@ phases:
         inputs:
           commands:
             - |
+              # TODO Validate rstudio server
+              # /usr/lib/rstudio-server/bin/rserver
               if type -P R &>/dev/null; then
                   echo "The R command exists."
               else
