image builder

diff --git a/files/image-builder/alinux2/singularity-component.yaml b/files/image-builder/alinux2/singularity-component.yaml
--- a/files/image-builder/alinux2/singularity-component.yaml
+++ b/files/image-builder/alinux2/singularity-component.yaml
@@ -49,26 +49,42 @@ phases:
               # TODO
               # Only supporting AWS Linux 2 based amis at this time
 
-              export TASK="Singularity"
-              echo "===================================================="
-              echo "# Starting: ${TASK}"
-              echo "===================================================="
+              ################################################
+              # Install Singularity / Apptainer
+              # https://github.com/apptainer/apptainer
+              ################################################
 
-              apt-get install -y \
-                build-essential \
-                libssl-dev \
-                uuid-dev \
-                libgpgme11-dev \
-                squashfs-tools \
-                libseccomp-dev \
+              # Install packages
+              echo "Installing system packages"
+              sudo amazon-linux-extras install -y epel
+              sudo yum-config-manager --enable epel
+              sudo yum update -y; yum upgrade -y
+              sudo yum group install -y 'Development Tools'
+
+              sudo yum install -y fuse3-devel
+              wget http://mirror.centos.org/centos/7/extras/x86_64/Packages/fuse-overlayfs-0.7.2-6.el7_8.x86_64.rpm
+              sudo yum localinstall -y fuse-overlayfs-0.7.2-6.el7_8.x86_64.rpm
+
+              sudo yum update -y
+
+              sudo yum install -y --quiet --skip-broken \
+                golang \
+                openssl-devel \
+                libuuid-devel \
+                libseccomp-devel \
                 wget \
-                pkg-config \
-                git
+                squashfs-tools \
+                libseccomp-devel \
+                squashfuse \
+                fakeroot \
+                cryptsetup \
+                wget git
 
-              wget -O- http://neuro.debian.net/lists/focal.us-nh.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
-              apt-key adv --recv-keys --keyserver hkps://keyserver.ubuntu.com 0xA5D32F012649A5A9
-              apt-get update -y
-              apt-get install -y singularity-container
+              sudo yum install -y --skip-broken \
+                apptainer
+
+              sudo yum install -y singularity \
+                  singularity-runtime || echo "Unable to install singularity"
 
   - name: validate
     steps:
diff --git a/files/image-builder/ubuntu2004/base-packages-component.yaml b/files/image-builder/ubuntu2004/base-packages-component.yaml
--- a/files/image-builder/ubuntu2004/base-packages-component.yaml
+++ b/files/image-builder/ubuntu2004/base-packages-component.yaml
@@ -108,117 +108,117 @@ phases:
               apt install -y nodejs || echo "Unable to install nodejs"
               npm install -g configurable-http-proxy
 
-      - name: validate
-        steps:
-          - name: ValidateLmod
-            action: ExecuteBash
-            inputs:
-              commands:
-                - |
-                  FILE="/usr/share/lmod/lmod/init/bash"
-                  if [ -f "$FILE" ]; then
-                      echo "$FILE exists."
-                  else
-                      echo "$FILE does not exist."
-                  fi
-          - name: ValidateAria2
-            action: ExecuteBash
-            inputs:
-              commands:
-                - |
-                  if type -P aria2c &>/dev/null; then
-                      echo "The aria2c command exists."
-                  else
-                      echo "The aria2c command does not exist. Failing."
-                      exit 1
-                  fi
-          - name: ValidateHtop
-            action: ExecuteBash
-            inputs:
-              commands:
-                - |
-                  if type -P htop &>/dev/null; then
-                      echo "The htop command exists."
-                  else
-                      echo "The htop command does not exist. Failing."
-                      exit 1
-                  fi
-          - name: ValidateTree
-            action: ExecuteBash
-            inputs:
-              commands:
-                - |
-                  if type -P tree &>/dev/null; then
-                      echo "The tree command exists."
-                  else
-                      echo "The tree command does not exist. Failing."
-                      exit 1
-                  fi
-          - name: ValidateAnsible
-            action: ExecuteBash
-            inputs:
-              commands:
-                - |
-                  if type -P ansible-galaxy &>/dev/null; then
-                      echo "The ansible-galaxy command exists."
-                  else
-                      echo "The ansible-galaxy command does not exist. Failing."
-                      exit 1
-                  fi
+  - name: validate
+    steps:
+      - name: ValidateLmod
+        action: ExecuteBash
+        inputs:
+          commands:
+            - |
+              FILE="/usr/share/lmod/lmod/init/bash"
+              if [ -f "$FILE" ]; then
+                  echo "$FILE exists."
+              else
+                  echo "$FILE does not exist."
+              fi
+      - name: ValidateAria2
+        action: ExecuteBash
+        inputs:
+          commands:
+            - |
+              if type -P aria2c &>/dev/null; then
+                  echo "The aria2c command exists."
+              else
+                  echo "The aria2c command does not exist. Failing."
+                  exit 1
+              fi
+      - name: ValidateHtop
+        action: ExecuteBash
+        inputs:
+          commands:
+            - |
+              if type -P htop &>/dev/null; then
+                  echo "The htop command exists."
+              else
+                  echo "The htop command does not exist. Failing."
+                  exit 1
+              fi
+      - name: ValidateTree
+        action: ExecuteBash
+        inputs:
+          commands:
+            - |
+              if type -P tree &>/dev/null; then
+                  echo "The tree command exists."
+              else
+                  echo "The tree command does not exist. Failing."
+                  exit 1
+              fi
+      - name: ValidateAnsible
+        action: ExecuteBash
+        inputs:
+          commands:
+            - |
+              if type -P ansible-galaxy &>/dev/null; then
+                  echo "The ansible-galaxy command exists."
+              else
+                  echo "The ansible-galaxy command does not exist. Failing."
+                  exit 1
+              fi
 
-                  ansible-galaxy --version
-                  if [[ $? == 0 ]]; then
-                      echo "ansible-galaxy was successfully invoked."
-                  else
-                      echo "ansible-galaxy could not be invoked. Failing."
-                      exit 1
-                  fi
-          - name: ValidateNodejs
-            action: ExecuteBash
-            inputs:
-              commands:
-                - |
-                  if type -P node &>/dev/null; then
-                      echo "The node command exists."
-                  else
-                      echo "The node command does not exist. Failing."
-                      exit 1
-                  fi
+              ansible-galaxy --version
+              if [[ $? == 0 ]]; then
+                  echo "ansible-galaxy was successfully invoked."
+              else
+                  echo "ansible-galaxy could not be invoked. Failing."
+                  exit 1
+              fi
+      - name: ValidateNodejs
+        action: ExecuteBash
+        inputs:
+          commands:
+            - |
+              if type -P node &>/dev/null; then
+                  echo "The node command exists."
+              else
+                  echo "The node command does not exist. Failing."
+                  exit 1
+              fi
 
-                  node --version
-                  if [[ $? == 0 ]]; then
-                      echo "node was successfully invoked."
-                  else
-                      echo "node could not be invoked. Failing."
-                      exit 1
-                  fi
-          - name: ConfigurableHttpProxy
-            action: ExecuteBash
-            inputs:
-              commands:
-                - |
-                  if type -P configurable-http-proxy &>/dev/null; then
-                      echo "The configurable-http-proxy command exists."
-                  else
-                      echo "The configurable-http-proxy command does not exist. Failing."
-                      exit 1
-                  fi
+              node --version
+              if [[ $? == 0 ]]; then
+                  echo "node was successfully invoked."
+              else
+                  echo "node could not be invoked. Failing."
+                  exit 1
+              fi
+      - name: ConfigurableHttpProxy
+        action: ExecuteBash
+        inputs:
+          commands:
+            - |
+              if type -P configurable-http-proxy &>/dev/null; then
+                  echo "The configurable-http-proxy command exists."
+              else
+                  echo "The configurable-http-proxy command does not exist. Failing."
+                  exit 1
+              fi
 
-                  configurable-http-proxy --version
-                  if [[ $? == 0 ]]; then
-                      echo "configurable-http-proxy was successfully invoked."
-                  else
-                      echo "configurable-http-proxy could not be invoked. Failing."
-                      exit 1
-                  fi
-          - name: ValidateJava
-            action: ExecuteBash
-            inputs:
-              commands:
-                - |
-                  if type -P java &>/dev/null; then
-                      echo "The java command exists."
-                  else
-                      echo "The java command does not exist. Failing."
-                      exit 1
-                  fi
+              configurable-http-proxy --version
+              if [[ $? == 0 ]]; then
+                  echo "configurable-http-proxy was successfully invoked."
+              else
+                  echo "configurable-http-proxy could not be invoked. Failing."
+                  exit 1
+              fi
+      - name: ValidateJava
+        action: ExecuteBash
+        inputs:
+          commands:
+            - |
+              if type -P java &>/dev/null; then
+                  echo "The java command exists."
+              else
+                  echo "The java command does not exist. Failing."
+                  exit 1
+              fi
